apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: default
      protocol: layer2
      addresses:
      - 192.168.1.150-192.168.1.250

# Router DHCP setup: reserve addresses 150-250 for load balancer.